// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0qtwEJ1WEjMYLlVyCpSNSKM8Q9tK8LDM',
    appId: '1:365742207294:web:cdcdbdb5799b640dc4fc6f',
    messagingSenderId: '365742207294',
    projectId: 'proyecto-comedoralimentaperu',
    authDomain: 'proyecto-comedoralimentaperu.firebaseapp.com',
    storageBucket: 'proyecto-comedoralimentaperu.firebasestorage.app',
    measurementId: 'G-ZHMQZ2TKQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAecRbiYMpwSjpUxtbO90rK7oVGnBNUGco',
    appId: '1:365742207294:android:20166b1181179c37c4fc6f',
    messagingSenderId: '365742207294',
    projectId: 'proyecto-comedoralimentaperu',
    storageBucket: 'proyecto-comedoralimentaperu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQxYUM_ObRpIEd1QBDfuJOXoM3R-0wmgc',
    appId: '1:365742207294:ios:eaa39b42a956a808c4fc6f',
    messagingSenderId: '365742207294',
    projectId: 'proyecto-comedoralimentaperu',
    storageBucket: 'proyecto-comedoralimentaperu.firebasestorage.app',
    iosBundleId: 'com.example.alimentaperuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQxYUM_ObRpIEd1QBDfuJOXoM3R-0wmgc',
    appId: '1:365742207294:ios:eaa39b42a956a808c4fc6f',
    messagingSenderId: '365742207294',
    projectId: 'proyecto-comedoralimentaperu',
    storageBucket: 'proyecto-comedoralimentaperu.firebasestorage.app',
    iosBundleId: 'com.example.alimentaperuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0qtwEJ1WEjMYLlVyCpSNSKM8Q9tK8LDM',
    appId: '1:365742207294:web:de258130ff9cbc10c4fc6f',
    messagingSenderId: '365742207294',
    projectId: 'proyecto-comedoralimentaperu',
    authDomain: 'proyecto-comedoralimentaperu.firebaseapp.com',
    storageBucket: 'proyecto-comedoralimentaperu.firebasestorage.app',
    measurementId: 'G-HGTE615661',
  );

}